# Site settings
title: Redstone Games
email: helpdesk@redstonegames.mobi
url: https://redstonegames.mobi
description: "Welcome to Redstone Games. Publishing best casual games for mobile platforms!"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: '000000' #80B3FF
  secondary: 'ff0000' #FD6E8A
  secondary-dark: '000000' #A2122F

# Footer settings
footer:
  copyright: Redstone Games
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/redstonemobi
  - title: facebook
    url: https://www.facebook.com/redstonegames

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
